# Cloudflare Workers configuration for D1
name = "aura-hype-web"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# D1 Database binding
[[d1_databases]]
binding = "DB" # This is the name you'll use in your code (globalThis.DB)
database_name = "aura-hype-db"
database_id = "a30f05d6-4588-4788-86bc-9cdf11e79d49" 

# R2 Object Database
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "aura-hype-listing-images"
